org: nayeliguzman
service: api-s3

provider:
  name: aws
  runtime: python3.12
  memorySize: 256
  timeout: 30
  iam:
    role: arn:aws:iam::891498524793:role/LabRole

functions:
  lista_buckets:
    handler: lista_buckets.lambda_handler
    memorySize: 1024
    events:
      - http:
          path: /s3/lista-buckets
          method: get
          cors: true
          integration: lambda
          
  lista_objetos_bucket:
    handler: lista_objetos_bucket.lambda_handler
    events:
      - http:
          path: /s3/bucket/lista-objetos
          method: post
          cors: true
          integration: lambda

  # Nueva función: Crear un nuevo bucket
  crear_bucket:
    handler: crear_bucket.lambda_handler
    events:
      - http:
          path: /s3/bucket/crear
          method: post
          cors: true
          integration: lambda

  # Nueva función: Crear un directorio en un bucket existente
  crear_directorio:
    handler: crear_directorio.lambda_handler
    events:
      - http:
          path: /s3/bucket/crear-directorio
          method: post
          cors: true
          integration: lambda

  # Nueva función: Subir un archivo en un directorio de un bucket existente
  subir_archivo:
    handler: subir_archivo.lambda_handler
    events:
      - http:
          path: /s3/bucket/subir-archivo
          method: post
          cors: true
          integration: lambda

resources:
  Resources:
    # Crear el bucket S3 cuando se despliega
    BucketS3:
      Type: AWS::S3::Bucket
      Properties:
        BucketName: ${self:provider.environment.BUCKET_NAME}
        VersioningConfiguration:
          Status: Enabled
        AccessControl: Private
